INSERT INTO pcc_auth_system.partners 
(island, abr, region, partner_name, herd_code, contact_person, contact_number, barangay, district, municipality, province, is_active, coop_type, center_code)
VALUES
-- CAR Cordillera Administrative Region
('Luzon', 'CAR', 'Cordillera Administrative Region', NULL, 'DMMMSU', NULL, NULL, NULL, NULL, NULL, 'Kalinga', NULL, NULL, 'DMMMSU'),
('Luzon', 'CAR', 'Cordillera Administrative Region', 'Mountain Province State Polytechnic College', 'DMMMSU', NULL, NULL, NULL, NULL, NULL, 'Mt. Province', NULL, NULL, 'DMMMSU'),

-- I Ilocos Region
('Luzon', 'I', 'Ilocos Region', 'PCC at MMSU IH', 'MMSU', NULL, NULL, NULL, '2', 'Batac', 'Ilocos Norte', NULL, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'PCC at MMSU CBED DSWD Sterilized', 'MMSU', NULL, NULL, NULL, NULL, 'Batac', 'Ilocos Norte', NULL, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'PCC at MMSU CBED Deped Sterilized', 'MMSU', NULL, NULL, NULL, NULL, 'Batac', 'Ilocos Norte', NULL, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Camguidan SLP Asso.', 'MMSU', NULL, NULL, NULL, '2', 'Batac', 'Ilocos Norte', NULL, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Ilocano Artificial Inseminators Credit Cooperative', 'MMSU', NULL, NULL, NULL, '2', 'Solsona', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Marcos Dairy Raisers Association', 'MMSU', NULL, NULL, NULL, '1', 'Marcos', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Ilocano Artificial Inseminators Credit Cooperative', 'MMSU', NULL, NULL, NULL, '2', 'San Nicolas', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Timpuyog de San Marcelino SLPA', 'MMSU', NULL, NULL, NULL, '2', 'Dingras', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Pangnamnamaan ti Colo Multipurpose Cooperative', 'MMSU', NULL, NULL, NULL, '2', 'Batac', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'PalonGene Poolong SLPA', 'MMSU', NULL, NULL, NULL, '2', 'Vigan', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Sta. Asuncion SLPA', 'MMSU', NULL, NULL, NULL, '2', 'San Nicolas', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Linang Farmers Agriculture Cooperative', 'MMSU', NULL, NULL, NULL, '2', 'Batac', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'San Marcelino SLPA', 'MMSU', NULL, NULL, NULL, '2', 'Batac', 'Ilocos Norte', NULL, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Sumader Dairy Raisers Association', 'MMSU', NULL, NULL, NULL, '2', 'Batac', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'MAGCOTA Dairy Raisers Association', 'MMSU', NULL, NULL, NULL, '2', 'Batac', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Naregta Sustainable Livelihood Program Association', 'MMSU', NULL, NULL, NULL, '2', 'Solsona', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Rimat Sustainable Livelihood Program Association', 'MMSU', NULL, NULL, NULL, '2', 'Solsona', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Timpuyog Sustainable Livelihood Program Association', 'MMSU', NULL, NULL, NULL, '2', 'Solsona', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Puttao Solsona SLPA', 'MMSU', NULL, NULL, NULL, '2', 'Solsona', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Piddig Basi Multi-Purpose Cooperative', 'MMSU', NULL, NULL, NULL, '1', 'Piddig', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Saud/Aring/Parang SLPA', 'MMSU', NULL, NULL, NULL, '2', 'Badoc', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Pugaoan Pinili SLPA', 'MMSU', NULL, NULL, NULL, '2', 'Pinili', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Barikir SLP Asso.', 'MMSU', NULL, NULL, NULL, '2', 'Pinili', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Timpuyog ti Imelda Farmers Ass, Inc.', 'MMSU', NULL, NULL, NULL, '2', 'Marcos', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Imelda Marcos SLPA', 'MMSU', NULL, NULL, NULL, '2', 'Marcos', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Elizabeth Marcos SLPA', 'MMSU', NULL, NULL, NULL, '2', 'Marcos', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Riverside Rainfed Upland Farmers Ass., Inc.', 'MMSU', NULL, NULL, NULL, '1', 'Bangui', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Ablan-Bayog-Bobon (ABB) Buffalo Raisers SLPA', 'MMSU', NULL, NULL, NULL, '1', 'Burgos', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Burgos Agro-Industrial School', 'MMSU', NULL, NULL, NULL, '1', 'Burgos', 'Ilocos Norte', NULL, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Mabanbanag/Namoroc SLPA', 'MMSU', NULL, NULL, NULL, '1', 'Vintar', 'Ilocos Norte', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Provincial Government of Ilocos Sur- Provincial Vet. Office', 'MMSU', NULL, NULL, NULL, '2', 'Marcos', 'Ilocos Sur', NULL, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Northern Ilocos Sur Agriculture Cooperative (NEW)', 'MMSU', NULL, NULL, NULL, '1', 'Cabugao', 'Ilocos Sur', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Nueva Segovia Consortium of Cooperative', 'MMSU', NULL, NULL, NULL, '1', 'Caoayan', 'Ilocos Sur', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Vigan Dairy Farmers Cooperative', 'MMSU', NULL, NULL, NULL, '1', 'Vigan', 'Ilocos Sur', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Salcedo Carabao Raisers Sustainable Livelihood Program Asso', 'MMSU', NULL, NULL, NULL, '1', 'Salcedo', 'Ilocos Sur', 1, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Ilocos Sur Polytechnic State College', 'MMSU', NULL, NULL, NULL, '1', 'Sta Maria', 'Ilocos Sur', NULL, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Private Dairy Farmers Antero Pimentel Jr.', 'MMSU', NULL, NULL, NULL, '1', 'Bantay', 'Ilocos Sur', NULL, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Private Dairy Farmers Ernesto Ganutan', 'MMSU', NULL, NULL, NULL, '2', 'Dingras', 'Ilocos Norte', NULL, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Private Dairy Farmers Rhommel Gamponia', 'MMSU', NULL, NULL, NULL, '2', 'Badoc', 'Ilocos Norte', NULL, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Private Dairy Farmers Lumbo, Alex', 'MMSU', NULL, NULL, NULL, '1', 'Banna', 'Ilocos Norte', NULL, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Private Dairy Farmers Rodriguez, Fredelito', 'MMSU', NULL, NULL, NULL, '1', 'San Juan', 'Ilocos Sur', NULL, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Private Dairy Farmers Siababa, Bonifacio', 'MMSU', NULL, NULL, NULL, '1', 'Cabugao', 'Ilocos Sur', NULL, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Private Dairy Farmers Eusebio Marcos', 'MMSU', NULL, NULL, NULL, '2', 'Dingras', 'Ilocos Norte', NULL, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Siababa, Bonifacio', 'MMSU', NULL, NULL, NULL, '1', 'Cabugao', 'Ilocos Sur', NULL, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Rodriguez, Fredelito', 'MMSU', NULL, NULL, NULL, '1', 'San Juan', 'Ilocos Sur', NULL, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Zumel, Arsenio', 'MMSU', NULL, NULL, NULL, '1', 'Solsona', 'Ilocos Norte', NULL, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Baltazar, Ferdinand', 'MMSU', NULL, NULL, NULL, '1', 'San Nicolas', 'Ilocos Norte', NULL, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Quiling Sur SLPA Asso.', 'MMSU', NULL, NULL, NULL, '2', 'Batac', 'Ilocos Norte', NULL, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Assisted Private Farmers', 'MMSU', NULL, NULL, NULL, NULL, NULL, 'Ilocos Norte', NULL, NULL, 'MMSU'),
('Luzon', 'I', 'Ilocos Region', 'Commulative Milk Fed to Calves July- September', 'MMSU', NULL, NULL, NULL, NULL, NULL, 'Ilocos Norte/Ilocos Sur/ Abra', NULL, NULL, 'MMSU'),

-- I Ilocos Region - DMMMSU
('Luzon', 'I', 'Ilocos Region', 'PCC Ranch', 'DMMMSU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'DMMMSU'),
('Luzon', 'I', 'Ilocos Region', 'Bantog Samahang Nayon Multipurpose Cooperative', 'DMMMSU', NULL, NULL, NULL, '4', 'Asingan', 'Pangasinan', 1, NULL, 'DMMMSU'),
('Luzon', 'I', 'Ilocos Region', 'Alaminos City', 'DMMMSU', NULL, NULL, NULL, '4', 'Alaminos City', 'Pangasinan', 1, NULL, 'DMMMSU'),
('Luzon', 'I', 'Ilocos Region', 'ELYU Farmers Multipurpose Cooperative (previously Rosario Dairy Farmers Cooperative', 'DMMMSU', NULL, NULL, NULL, '2', 'Rosario', 'La Union', 1, NULL, 'DMMMSU'),
('Luzon', 'I', 'Ilocos Region', 'Aringay Dairy Carabao Raisers Association', 'DMMMSU', NULL, NULL, NULL, '2', 'Aringay', 'La Union', 1, NULL, 'DMMMSU'),
('Luzon', 'I', 'Ilocos Region', 'BAUANG (Tejano, Ruben)', 'DMMMSU', NULL, NULL, NULL, '2', 'Bauang', 'La Union', NULL, NULL, 'DMMMSU'),
('Luzon', 'I', 'Ilocos Region', 'BACNOTAN (E. Ringor,P. Obra,F. Riña,G. Posadas)', 'DMMMSU', NULL, NULL, NULL, '1', 'Bacnotan', 'La Union', NULL, NULL, 'DMMMSU'),
('Luzon', 'I', 'Ilocos Region', 'Team Naguilian Dairy Raisers Asso.', 'DMMMSU', NULL, NULL, NULL, '2', 'Naguillan', 'La Union', 1, NULL, 'DMMMSU'),
('Luzon', 'I', 'Ilocos Region', 'Sudipen Dairy Farmers Asso.', 'DMMMSU', NULL, NULL, NULL, '1', 'Sudipen', 'La Union', 1, NULL, 'DMMMSU'),
('Luzon', 'I', 'Ilocos Region', 'Dasol Dairy Buffalo Raisers Association', 'DMMMSU', NULL, NULL, NULL, '1', 'Dasol', 'Pangasinan', 1, NULL, 'DMMMSU'),
('Luzon', 'I', 'Ilocos Region', 'Laoac', 'DMMMSU', NULL, NULL, NULL, '4', 'Laoac', 'Pangasinan', NULL, NULL, 'DMMMSU'),

-- II Cagayan Valley
('Luzon', 'II', 'Cagayan Valley', 'PCC at CSU IH', 'CSU', NULL, NULL, NULL, '3', 'Piat', 'Cagayan', 0, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Piat Dairy Cooperative (PIDACO)', 'CSU', NULL, NULL, NULL, '3', 'Piat', 'Cagayan', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Integrated Farmers Cooperative', 'CSU', NULL, NULL, NULL, '3', 'Tuguegarao', 'Cagayan', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Andarayan North & South Crossbred Buffalo Owners Dairy Association (ANSCBODA)', 'CSU', NULL, NULL, NULL, '3', 'Solana', 'Cagayan', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Bangag Carabao Owners Dairy Association (BCODA)', 'CSU', NULL, NULL, NULL, '3', 'Solana', 'Cagayan', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Bauan West Carabao Owbers Dairy Association (BWCODA)', 'CSU', NULL, NULL, NULL, '3', 'Solana', 'Cagayan', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Bical Baliwag Agrarian Reform Beneficiaries Cooperative(BBARBC)', 'CSU', NULL, NULL, NULL, '3', 'Penablanca', 'Cagayan', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Cattaran Crossbred Owners Dairy Association (CCODA)', 'CSU', NULL, NULL, NULL, '3', 'Solana', 'Cagayan', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Dairy Multipurpose Cooperative Inc.', 'CSU', NULL, NULL, NULL, '3', 'Ballacayu', 'Cagayan', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Dassun Dairy Carabao Producers & Livestock Association (DDCPLA)', 'CSU', NULL, NULL, NULL, '3', 'Solana', 'Cagayan', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Gen. Balao Dairy Multipurpose Cooperative Inc.', 'CSU', NULL, NULL, NULL, '3', 'Solana', 'Cagayan', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Hacienda Intal Credit Cooperative', 'CSU', NULL, NULL, NULL, '1', 'Baggao', 'Cagayan', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Amianan Coconut Farmers Association', 'CSU', NULL, NULL, NULL, '1', 'Baggao', 'Cagayan', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Sampaguita Livestock Producer Dairy Association (SLPDA)', 'CSU', NULL, NULL, NULL, '3', 'Solana', 'Cagayan', 0, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'San Antonio Dairy Carabao Raisers Association (SADCRA)', 'CSU', NULL, NULL, NULL, '3', 'Lallo', 'Cagayan', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Yum Wah Incorporated (YWInc.)', 'CSU', NULL, NULL, NULL, '3', 'Penablanca', 'Cagayan', NULL, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Cagayan Valley Development Cooperative (CAVADECO)', 'CSU', NULL, NULL, NULL, '3', 'Solana', 'Cagayan', 0, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Cagayan-Apayao Farmers Development Association', 'CSU', NULL, NULL, NULL, '3', 'Lallo', 'Cagayan', 0, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Timpuyug Dagiti Naballigi nga Mannalon Association (TDNMA)', 'CSU', NULL, NULL, NULL, '3', 'Amulung', 'Cagayan', NULL, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Bagunot Marketing Cooperative (BMC)', 'CSU', NULL, NULL, NULL, '1', 'Baggao', 'Cagayan', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Domingo Baggayan', 'CSU', NULL, NULL, NULL, '3', 'Solana', 'Cagayan', NULL, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Maguirig Carabao Owners Dairy Association', 'CSU', NULL, NULL, NULL, '3', 'Solana', 'Cagayan', 0, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Bacring Dairy Farmers Association', 'CSU', NULL, NULL, NULL, '3', 'Amulung', 'Cagayan', 0, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Bayabat Carabao Owners Dairy Association', 'CSU', NULL, NULL, NULL, '3', 'Amulung', 'Cagayan', 0, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Masical Dairy Farmers Association', 'CSU', NULL, NULL, NULL, '2', 'Sto Nino', 'Cagayan', 0, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Afusing Daga Carabao Owners Association', 'CSU', NULL, NULL, NULL, '1', 'Afusing', 'Cagayan', 0, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Dairy Association of Malalatan', 'CSU', NULL, NULL, NULL, '1', 'Alcala', 'Cagayan', 0, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Tamban Carabao Owners Dairy Association', 'CSU', NULL, NULL, NULL, '1', 'Alcala', 'Cagayan', 0, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Alcala Sweet Candy(processor)', 'CSU', NULL, NULL, NULL, '1', 'Alcala', 'Cagayan', NULL, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Rang-ay Ti - Pussian Farmers Cooperative', 'CSU', NULL, NULL, NULL, '1', 'Alcala', 'Cagayan', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Tanap Greening Producer Cooperatives', 'CSU', NULL, NULL, NULL, '3', 'Tuguegarao', 'Cagayan', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Pinoy Bagong Pag-asa Marketing Cooperative (for finalization)', 'CSU', NULL, NULL, NULL, '3', 'Tuao', 'Cagayan', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Firm Foundation Agricultural Cooperative (FFAC)', 'CSU', NULL, NULL, NULL, '3', 'Tuao', 'Cagayan', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Pagsanggiran Ti Mannalon Multi-Purpose Cooperative', 'CSU', NULL, NULL, NULL, '2', 'Abulug', 'Cagayan', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Nueva Vizcaya Rebel Returnees Association Inc.', 'CSU', NULL, NULL, NULL, '1', 'Bayombong', 'Nueva Vizcaya', 0, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Nueva Viscaya Farmers Livestock Raisers Multipurpose Cooperative', 'CSU', NULL, NULL, NULL, '1', 'Bambang', 'Nueva Vizcaya', 0, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Amancio Agri-Tourism Dairy Cooperative (AATDC)', 'CSU', NULL, NULL, NULL, '1', 'Cordon', 'Nueva Vizcaya', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Saint Vincent Parish Multipurpose Cooperative', 'CSU', NULL, NULL, NULL, '1', 'Dupax Del Sur', 'Nueva Vizcaya', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Quirino Dairy Cooperative', 'CSU', NULL, NULL, NULL, '1', 'Aglipay', 'Quirino', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Quirino State College', 'CSU', NULL, NULL, NULL, '1', 'Diffun', 'Quirino', NULL, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'San Pablo Isabela Farmers Dairy Cooperative (SPIFDC)', 'CSU', NULL, NULL, NULL, '1', 'San Pablo', 'Isabela', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'San Agustin Dairy Cooperative', 'CSU', NULL, NULL, NULL, '4', 'San Agustin', 'Isabela', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'San Agustin Dairy Cooperative (Collected Non-members)', 'CSU', NULL, NULL, NULL, '4', 'San Agustin', 'Isabela', 0, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Isabela State University', 'CSU', NULL, NULL, NULL, '6', 'Echague', 'Isabela', NULL, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Liga ng mga Barangay  ng Isabela Multipurpose Cooperative', 'CSU', NULL, NULL, NULL, '6', 'Echague', 'Isabela', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Klinika Farmers Association of Capellan', 'CSU', NULL, NULL, NULL, NULL, 'Ilagan', 'Isabela', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'Cabagan Dairy Produce Association', 'CSU', NULL, NULL, NULL, NULL, 'Cabagan', 'Isabela', 1, NULL, 'CSU'),
('Luzon', 'II', 'Cagayan Valley', 'SEGOVIA''s Finest Lallo Milk candy', 'CSU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'CSU'),

-- III Central Luzon
('Luzon', 'III', 'Central Luzon', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Aurora', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'PCCNHQGene Pool IH', 'Gene Pool', NULL, NULL, NULL, NULL, NULL, 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Catalanacan Multi-Purpose Cooperative', 'NIZ', NULL, NULL, NULL, '2', 'Science City of Munoz', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Eastern Primary Multi Purpose Cooperative', 'NIZ', NULL, NULL, NULL, '2', 'San Jose City', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Pulong Buli Primary Multi Purpose Cooperative', 'NIZ', NULL, NULL, NULL, '1', 'Santo Domingo', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'DVF Dairy Farm (Family Module)', 'NIZ', NULL, NULL, NULL, '1', 'Talavera', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'NEFEDCO', 'NIZ', NULL, NULL, NULL, '2', 'Llanera', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'ACDI', 'NIZ', NULL, NULL, NULL, '2', 'San Jose City', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Licaong Agriculture Cooperative', 'NIZ', NULL, NULL, NULL, '2', 'Science City of Munoz', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Brothers Keeper Multi Purpose Cooperative', 'NIZ', NULL, NULL, NULL, '2', 'San Jose City', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Simula ng Panibagong Bukas Multi Purpose Cooperative', 'NIZ', NULL, NULL, NULL, '2', 'San Jose City', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Ayos Lomboy Dairy Cooperative', 'NIZ', NULL, NULL, NULL, '1', 'Guimba', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Bagong Pag-asa sa Bagong Talavera PMultipurpose Cooperative', 'NIZ', NULL, NULL, NULL, '1', 'Talavera', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Bongabon Dairy Association (CB Module)', 'NIZ', NULL, NULL, NULL, '3', 'Bongabon', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Bosque Primary Multi-purpose Cooperative', 'NIZ', NULL, NULL, NULL, '2', 'Llanera', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Buklod Producers Cooperative', 'NIZ', NULL, NULL, NULL, '3', 'Gen. Natividad', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Buliran Crossbreds Community (CB Module)', 'NIZ', NULL, NULL, NULL, '4', 'San Antonio', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Caudillo Prutas at Gulay Producer Cooperative', 'NIZ', NULL, NULL, NULL, '3', 'Cabanatuan', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Cinense Dairy Producers Cooperative', 'NIZ', NULL, NULL, NULL, '2', 'Talugtug', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Gabay sa Bagong Pag-asa ng Bungo', 'NIZ', NULL, NULL, NULL, '4', 'Gapan', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Makabagong Kooperatiba ng Bantug PMultipurpose Cooperative', 'NIZ', NULL, NULL, NULL, '1', 'Talavera', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Maliolio Dairy Carabao Association', 'NIZ', NULL, NULL, NULL, '3', 'Sta. Rosa', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Nag-iisang Masikap Primary Multi Purpose Cooperative', 'NIZ', NULL, NULL, NULL, '3', 'Gen. Natividad', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Palayan SCOA', 'NIZ', NULL, NULL, NULL, '1', 'Palayan', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'San Carlos Agricultural Cooperative', 'NIZ', NULL, NULL, NULL, '1', 'Aliaga', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Jaen Farmers Association', 'NIZ', NULL, NULL, NULL, '4', 'Jaen', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Tallar''s Dairy Farm', 'NIZ', NULL, NULL, NULL, '2', 'Lupao', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Melchor Correa (Family Module)', 'NIZ', NULL, NULL, NULL, '2', 'San Jose City', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Delaen Agriculture Cooperative', 'NIZ', NULL, NULL, NULL, '2', 'San Jose City', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Callo''s Dairy Farm', 'NIZ', NULL, NULL, NULL, '2', 'Science City of Munoz', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Raul Lara', 'NIZ', NULL, NULL, NULL, '2', 'Science City of Munoz', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Bibiclat Dairy Producers Cooperative', 'NIZ', NULL, NULL, NULL, '1', 'Aliaga', 'Nueva Ecija', 1, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Abergas Dairy Farm', 'NIZ', NULL, NULL, NULL, '4', 'San Leonardo', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Nievera''s Dairy Farm', 'NIZ', NULL, NULL, NULL, '1', 'Guimba', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Calapini''s Dairy Farm', 'NIZ', NULL, NULL, NULL, '2', 'Caranglan', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Lina Clemente''s Dairy Farm', 'NIZ', NULL, NULL, NULL, '2', 'Caranglan', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Gapan City(Makabaklay, Malimba, Sto. Cristo, San Nicolas, San Roque, Bulak, Pambuan)', 'NIZ', NULL, NULL, NULL, '4', 'Gapan', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Serame''s Dairy Farm', 'NIZ', NULL, NULL, NULL, '2', 'Rizal', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Cabacungan''s Dairy Farm', 'NIZ', NULL, NULL, NULL, '1', 'Aliaga', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Aranilla''s Dairy Farm', 'NIZ', NULL, NULL, NULL, '4', 'Peñaranda', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'AJ''s Farm', 'NIZ', NULL, NULL, NULL, '3', 'Sta. Rosa', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Pagas Dairy Farm', 'NIZ', NULL, NULL, NULL, '3', 'Cabanatuan', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Delos Reyes Dairy Farm', 'NIZ', NULL, NULL, NULL, '3', 'Cabanatuan', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Vega Bongabon', 'NIZ', NULL, NULL, NULL, '3', 'Bongabon', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Marcos Dairy Farm', 'NIZ', NULL, NULL, NULL, '1', 'Talavera', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Lean & Joel Farm', 'NIZ', NULL, NULL, NULL, '2', 'San Jose City', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'San Alejandro', 'NIZ', NULL, NULL, NULL, '1', 'Quezon', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Taktak buffalo raiser''s', 'NIZ', NULL, NULL, NULL, '2', 'Caranglan', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Val Vergel Farm', 'NIZ', NULL, NULL, NULL, '2', 'Rizal', 'Nueva Ecija', NULL, NULL, NULL),
('Luzon', 'III', 'Central Luzon', 'Milk Fed to calves', 'NIZ', NULL, NULL, NULL, NULL, NULL, 'Nueva Ecija', NULL, NULL, NULL),

-- III Central Luzon - CLSU
('Luzon', 'III', 'Central Luzon', 'PCC AT CLSU IH', 'CLSU', NULL, NULL, NULL, '4', 'Muñoz', 'Nueva Ecija', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Milk Feeding Sales( Region III )', 'CLSU', NULL, NULL, NULL, NULL, NULL, 'Nueva Ecija', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Luzon Dairy Cooperative', 'CLSU', NULL, NULL, NULL, '6', 'Sta. Maria', 'Nueva Ecija', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Samahang Pangkaunlaran ng Magsasaka Sa Calancuasan Irrigators Association Corp.', 'CLSU', NULL, NULL, NULL, NULL, 'Cuyapo', 'Nueva Ecija', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Ferdie Delos Reyes', 'CLSU', NULL, NULL, NULL, NULL, 'Sta. Rosa', 'Nueva Ecija', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Labne Producers Cooperative', 'CLSU', NULL, NULL, NULL, '3', 'San Miguel', 'Bulacan', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Malibay Aggressive Multipurpose Cooperative', 'CLSU', NULL, NULL, NULL, '3', 'San Miguel', 'Bulacan', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Sta. Lucia SMB FA', 'CLSU', NULL, NULL, NULL, '3', 'San Miguel', 'Bulacan', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Catmon Multipurpose Cooperative', 'CLSU', NULL, NULL, NULL, '3', 'Sta. Maria', 'Bulacan', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Lambakin Agricultural Marketing Cooperative', 'CLSU', NULL, NULL, NULL, '3', 'San Miguel', 'Bulacan', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Malibay Crossbred Owners', 'CLSU', NULL, NULL, NULL, '3', 'San Miguel', 'Bulacan', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Milk Collectors of San Miguel Bulacan', 'CLSU', NULL, NULL, NULL, '3', 'San Miguel', 'Bulacan', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Pulilan Milk Producers Asso', 'CLSU', NULL, NULL, NULL, '1', 'Pulilan', 'Bulacan', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Buhol na Mangga Marketing Cooperative', 'CLSU', NULL, NULL, NULL, '3', 'San Ildefonso', 'Bulacan', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Makapilapil Farmers Association', 'CLSU', NULL, NULL, NULL, '3', 'San Ildefonso', 'Bulacan', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'San Ildefonso Farmers and Carabao Association', 'CLSU', NULL, NULL, NULL, '3', 'San Ildefonso', 'Bulacan', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'San Roque Dairy Farmers Association', 'CLSU', NULL, NULL, NULL, '2', 'Baliuag', 'Bulacan', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Adriano, Adelpha', 'CLSU', NULL, NULL, NULL, NULL, 'Sta. Maria', 'Bulacan', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Alejandro, Leoncio', 'CLSU', NULL, NULL, NULL, '3', 'San Miguel', 'Bulacan', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Rommel Santiago', 'CLSU', NULL, NULL, NULL, '6', 'Sta. Maria', 'Bulacan', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Frederick Pengson', 'CLSU', NULL, NULL, NULL, '3', 'San Miguel', 'Bulacan', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Area Farmers Agriculture Association', 'CLSU', NULL, NULL, NULL, '3', 'San Miguel', 'Bulacan', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Allied Christian Agrarian Reform Cooperative (ACAR)', 'CLSU', NULL, NULL, NULL, '3', 'San Miguel', 'Bulacan', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Angat, Bulacan (Private Cluster)', 'CLSU', NULL, NULL, NULL, NULL, 'San Miguel', 'Bulacan', 0, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Roberto David and (Private Cluster)', 'CLSU', NULL, NULL, NULL, '2', 'Porac', 'Pampanga', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Ronaldo Bautista', 'CLSU', NULL, NULL, NULL, '2', 'Lubao', 'Pampanga', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Candaba Pampanga( Private Cluster)', 'CLSU', NULL, NULL, NULL, NULL, 'Candaba', 'Pampanga', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Pampanga UpUp DPA', 'CLSU', NULL, NULL, NULL, '1', 'Bacolor', 'Pampanga', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Villa de Bacolor DFA', 'CLSU', NULL, NULL, NULL, '1', 'Bacolor', 'Pampanga', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Bacolor( Private )', 'CLSU', NULL, NULL, NULL, '1', 'Bacolor', 'Pampanga', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Raymond Garcia', 'CLSU', NULL, NULL, NULL, '4', 'Lubao', 'Pampanga', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Umpucan Multipurpose Cooperative', 'CLSU', NULL, NULL, NULL, '4', 'San Ildefonso', 'Pampanga', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'KNT Dairy Farm', 'CLSU', NULL, NULL, NULL, NULL, NULL, 'Pampanga', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Arayat Pampanga (Private Cluster)', 'CLSU', NULL, NULL, NULL, NULL, 'Arayat', 'Pampanga', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Pasamonte Brothers', 'CLSU', NULL, NULL, NULL, '3', 'San Fernando City', 'Pampanga', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Ronald ponce', 'CLSU', NULL, NULL, NULL, '1', 'Angeles', 'Pampanga', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'United Farmer Clark Pampanga(New)', 'CLSU', NULL, NULL, NULL, '1', 'Angeles', 'Pampanga', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', NULL, 'CLSU', NULL, NULL, NULL, '3', 'San Fernando City', 'Jesus Tulabot', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Floridablanca, Pampanga (Private Cluster)', 'CLSU', NULL, NULL, NULL, '1', 'Florida', 'Pampanga', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Caryana Community', 'CLSU', NULL, NULL, NULL, '1', 'Magalang', 'Pampanga', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Jalungian''s Farmers Agriculture Cooperative', 'CLSU', NULL, NULL, NULL, '1', 'Magalang', 'Pampanga', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Sta. Maria Dairy Farmers Association', 'CLSU', NULL, NULL, NULL, '1', 'Magalang', 'Pampanga', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Lubao, Pampanga (Private Cluster)', 'CLSU', NULL, NULL, NULL, '2', 'Lubao', 'Pampanga', 0, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Lubao Farmers and Fisherfolks Agriculture Cooperative', 'CLSU', NULL, NULL, NULL, '2', 'Lubao', 'Pampanga', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Magalang Pampanga ( Private Cluster )', 'CLSU', NULL, NULL, NULL, '1', 'Magalang', 'Pampanga', 0, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Bataan Farmers Agri Cooperative', 'CLSU', NULL, NULL, NULL, '2', 'Balanga', 'Bataan', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Makabagong Agrikultura ng Dinalupihan Marketing Cooperative', 'CLSU', NULL, NULL, NULL, '1', 'Dinalupihan', 'Bataan', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Campos, Jan Antonio', 'CLSU', NULL, NULL, NULL, '1', 'Samal', 'Bataan', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Tapulao Multipurpose Cooperative', 'CLSU', NULL, NULL, NULL, '1', 'Orani', 'Bataan', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Roming Food Product Milk Feeding Sales', 'CLSU', NULL, NULL, NULL, NULL, NULL, 'Bataan', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'AMIA Cruz Agriculture Cooperative', 'CLSU', NULL, NULL, NULL, '2', 'Victoria', 'Tarlac', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Palayamanan Producers Agriculture Cooperative', 'CLSU', NULL, NULL, NULL, '2', 'Victoria', 'Tarlac', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Mabulod Green Farm Producers  Cooperative', 'CLSU', NULL, NULL, NULL, '2', 'San Jose', 'Tarlac', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Adeline Dairy Farm', 'CLSU', NULL, NULL, NULL, NULL, 'Concepcion', 'Tarlac', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Concepcion Tarlac (Private Cluster)', 'CLSU', NULL, NULL, NULL, NULL, 'Concepcion', 'Tarlac', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Gerona Tarlac( Private Cluster )', 'CLSU', NULL, NULL, NULL, '1', 'Gerona', 'Tarlac', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Hermosa Tarlac ( Private Cluster )', 'CLSU', NULL, NULL, NULL, '1', 'Hermosa', 'Tarlac', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Allen Paul Santos and others', 'CLSU', NULL, NULL, NULL, '1', 'Tarlac City', 'Tarlac', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Joselito Tumang', 'CLSU', NULL, NULL, NULL, '3', 'Bamban', 'Tarlac', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'William Lagman', 'CLSU', NULL, NULL, NULL, '3', 'Bamban', 'Tarlac', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Cheng Farm', 'CLSU', NULL, NULL, NULL, '3', 'Moncada', 'Tarlac', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Capaz Tarlac( Private Cluster )', 'CLSU', NULL, NULL, NULL, NULL, 'Capaz', 'Tarlac', NULL, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Castillejos Farmers Agriculture Cooperative', 'CLSU', NULL, NULL, NULL, '1', 'Castillejos', 'Zambales', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Masinloc Farmers Cooperative', 'CLSU', NULL, NULL, NULL, '2', 'Masinloc', 'Zambales', 1, NULL, 'CLSU'),
('Luzon', 'III', 'Central Luzon', 'Sta. Catalina Farms', 'CLSU', NULL, NULL, NULL, '2', 'Botolan', 'Zambales', NULL, NULL, 'CLSU'),

-- IV-A Calabarzon
('Luzon', 'IV-A', 'Calabarzon', 'PCC at UPLB IH', 'UPLB', NULL, NULL, NULL, NULL, NULL, 'Laguna', NULL, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'LGU Magdalena Processing Facility', 'UPLB', NULL, NULL, NULL, '4', 'Magdalena', 'Laguna', NULL, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'Kalayaan Dairy Farmers Association', 'UPLB', NULL, NULL, NULL, '4', 'Kalayaan', 'Laguna', 1, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'Magdalena Agriculture Cooperative', 'UPLB', NULL, NULL, NULL, '4', 'Magdalena', 'Laguna', 1, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'Magdalena Dairy Raisers Association', 'UPLB', NULL, NULL, NULL, '4', 'Magdalena', 'Laguna', 1, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'Agarao Project', 'UPLB', NULL, NULL, NULL, NULL, 'Sta. Cruz', 'Laguna', 1, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'New PAGSANTA Producers Cooperative', 'UPLB', NULL, NULL, NULL, '4', 'Pagsanjan', 'Laguna', 1, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'San Pablo City Milkers Assoc', 'UPLB', NULL, NULL, NULL, '4', 'San Pablo', 'Laguna', 1, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'Lumban Cheesemakers (NEW)', 'UPLB', NULL, NULL, NULL, '4', 'Lumban', 'Laguna', NULL, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'General Trias Dairy Raisers Multi-Purpose Cooperative', 'UPLB', NULL, NULL, NULL, '6', 'Gen. Trias', 'Cavite', 1, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'Tanza Farmers Dairy Producers Cooperative', 'UPLB', NULL, NULL, NULL, '7', 'Tanza', 'Cavite', 1, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'Villar Sipag''', 'UPLB', NULL, NULL, NULL, '1', 'Bacoor', 'Cavite', NULL, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'The Rosario Livestock and Agriculture Farming Cooperative', 'UPLB', NULL, NULL, NULL, '2', 'Rosario', 'Batangas', 1, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'Balayan', 'UPLB', NULL, NULL, NULL, '1', 'Balayan', 'Batangas', 1, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'Calatagan Dairy Farmers Association', 'UPLB', NULL, NULL, NULL, '1', 'Calatagan', 'Batangas', 1, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'CABUPALO Dairy Farmers Association', 'UPLB', NULL, NULL, NULL, '1', 'Nasugbu', 'Batangas', 1, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'ACES PhilProducers Corporation', 'UPLB', NULL, NULL, NULL, '4', 'Ibaan', 'Batangas', NULL, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'Llano Farmers Multipurpose Cooperative', 'UPLB', NULL, NULL, NULL, '2', 'Jalajala', 'Rizal', 1, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'Jalajala Farmers Marketing Cooperative', 'UPLB', NULL, NULL, NULL, '2', 'Jalajala', 'Rizal', 1, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'Antipolo City, Rizal (NEW)', 'UPLB', NULL, NULL, NULL, NULL, 'Antipolo City', 'Rizal', NULL, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'Pililla Dairy Association', 'UPLB', NULL, NULL, NULL, '2', 'Pililla', 'Rizal', 0, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'Tanay, Rizal', 'UPLB', NULL, NULL, NULL, '2', 'Tanay', 'Rizal', NULL, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'Teresa, Rizal (NEW)', 'UPLB', NULL, NULL, NULL, NULL, 'Teresa', 'Rizal', NULL, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'San Mateo, Rizal', 'UPLB', NULL, NULL, NULL, '3', 'San Mateo', 'Rizal', 1, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'Dolores Farmers Association', 'UPLB', NULL, NULL, NULL, '1', 'Dolores', 'Quezon', 1, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'Lucban Dairy Buffalo Association, Inc.', 'UPLB', NULL, NULL, NULL, '1', 'Lucban', 'Quezon', 1, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'Tayabas Community MultiPurpose Cooperative', 'UPLB', NULL, NULL, NULL, '1', 'Tayabas', 'Quezon', 1, NULL, 'UPLB'),
('Luzon', 'IV-A', 'Calabarzon', 'Manggalang Agrarian Reform Beneficiaries Cooperative', 'UPLB', NULL, NULL, NULL, '1', 'Manggalang', 'Quezon', 1, NULL, 'UPLB'),

-- IV-B Southwestern Tagalog Region
('Luzon', 'IV-B', 'Southwestern Tagalog Region', 'Marinduque Diocesan Development Cooperative', 'UPLB', NULL, NULL, NULL, '1', 'Boac', 'Marinduque', 1, NULL, 'UPLB'),
('Luzon', 'IV-B', 'Southwestern Tagalog Region', NULL, 'UPLB', NULL, NULL, NULL, NULL, NULL, 'Occidental Mindoro', NULL, NULL, 'UPLB'),
('Luzon', 'IV-B', 'Southwestern Tagalog Region', 'Mindoro Dairy Cooperative', 'UPLB', NULL, NULL, NULL, '2', 'Bansud', 'Oriental Mindoro', 1, NULL, 'UPLB'),
('Luzon', 'IV-B', 'Southwestern Tagalog Region', 'Bongabong Dairy Buffalo of Oriental Mindoro and Producers Association (BDBOMPA)', 'UPLB', NULL, NULL, NULL, '2', 'Bansud', 'Oriental Mindoro', 1, NULL, 'UPLB'),
('Luzon', 'IV-B', 'Southwestern Tagalog Region', 'Tamaraw Development Cooperative', 'UPLB', NULL, NULL, NULL, '1', 'San Jose', 'Oriental Mindoro', 1, NULL, 'UPLB'),
('Luzon', 'IV-B', 'Southwestern Tagalog Region', 'Yamang Bukid Farm Palawan', 'UPLB', NULL, NULL, NULL, '2', 'PUERTO PRINCESA', 'Palawan', NULL, NULL, 'UPLB'),
('Luzon', 'IV-B', 'Southwestern Tagalog Region', NULL, 'UPLB', NULL, NULL, NULL, NULL, NULL, 'Romblon', NULL, NULL, 'UPLB'),

-- V Bicol Region
('Luzon', 'V', 'Bicol Region', 'Albay Dairy Processing', 'UPLB', NULL, NULL, NULL, '2', 'Camalig', 'Albay', 1, NULL, 'UPLB'),
('Luzon', 'V', 'Bicol Region', NULL, 'UPLB', NULL, NULL, NULL, NULL, NULL, 'Albay', NULL, NULL, 'UPLB'),
('Luzon', 'V', 'Bicol Region', 'Gubat St. Anthony Cooperative', 'UPLB', NULL, NULL, NULL, '2', 'Gubat', 'Sorsogon', 1, NULL, 'UPLB'),
('Luzon', 'V', 'Bicol Region', 'JSM Integrated Farm', NULL, NULL, NULL, NULL, NULL, NULL, 'Camarines Norte', NULL, NULL, NULL),
('Luzon', 'V', 'Bicol Region', 'Farmland Multipurpose Cooperative', 'UPLB', NULL, NULL, NULL, '1', 'Sipocot', 'Camarines Sur', 1, NULL, 'UPLB'),
('Luzon', 'V', 'Bicol Region', 'Pasacao Integrated Coconut Farmers Cooperative', 'UPLB', NULL, NULL, NULL, '2', 'Pasacao', 'Camarines Sur', 1, NULL, 'UPLB'),
('Luzon', 'V', 'Bicol Region', 'Camarines Sur Multi-Purpose Cooperative', 'UPLB', NULL, NULL, NULL, NULL, 'Pili', 'Camarines Sur', 1, NULL, 'UPLB'),
('Luzon', 'V', 'Bicol Region', NULL, 'UPLB', NULL, NULL, NULL, NULL, NULL, 'Catanduanes', NULL, NULL, 'UPLB'),
('Luzon', 'V', 'Bicol Region', NULL, 'USF', NULL, NULL, NULL, NULL, NULL, 'Masbate', NULL, NULL, 'USF'),

-- VI Western Visayas
('Visayas', 'VI', 'Western Visayas', '"Calimbajan Mainuswagong Panimaeay Consumers Cooperative (NEW) GMT Farmers Consumers Cooperative (NEW)"', 'WVSU', NULL, NULL, NULL, '2', 'Makato', 'Aklan', 1, NULL, 'WVSU'),
('Visayas', 'VI', 'Western Visayas', 'Nalook Farmers Association', 'WVSU', NULL, NULL, NULL, '2', 'Kalibo', 'Aklan', 1, NULL, 'WVSU'),
('Visayas', 'VI', 'Western Visayas', 'Integrated Barangays of Numancia Multi-Purpose Cooperative (IBON)', 'WVSU', NULL, NULL, NULL, '2', 'Numancia', 'Aklan', 1, NULL, 'WVSU'),
('Visayas', 'VI', 'Western Visayas', 'AGRACA Agrarian Reform Cooperative (AGRACA)', 'WVSU', NULL, NULL, NULL, '2', 'Dumalag', 'Capiz', 1, NULL, 'WVSU'),
('Visayas', 'VI', 'Western Visayas', 'Guimaras Employees Multipurpose Cooperative', 'WVSU', NULL, NULL, NULL, '1', 'Jordan', 'Guimaras', 1, NULL, 'WVSU'),
('Visayas', 'VI', 'Western Visayas', 'GUIMARAS-FATIMA', 'WVSU', NULL, NULL, NULL, NULL, NULL, 'Guimaras', NULL, NULL, 'WVSU'),
('Visayas', 'VI', 'Western Visayas', 'BFF', 'WVSU', NULL, NULL, NULL, NULL, 'Sibunag', 'Guimaras', NULL, NULL, 'WVSU'),
('Visayas', 'VI', 'Western Visayas', 'PCC at WVSU IH', 'WVSU', NULL, NULL, NULL, '3', 'Calinog', 'Iloilo', NULL, NULL, 'WVSU'),
('Visayas', 'VI', 'Western Visayas', 'Calinog Farmers Agriculture Cooperative', 'WVSU', NULL, NULL, NULL, '3', 'Calinog', 'Iloilo', 1, NULL, 'WVSU'),
('Visayas', 'VI', 'Western Visayas', 'Leon ConFed Farmers'' Dairy Association', 'WVSU', NULL, NULL, NULL, '2', 'Leon', 'Iloilo', 1, NULL, 'WVSU'),
('Visayas', 'VI', 'Western Visayas', 'George''s Farm (Private Module)', 'WVSU', NULL, NULL, NULL, '2', 'Zarraga', 'Iloilo', NULL, NULL, 'WVSU'),
('Visayas', 'VI', 'Western Visayas', 'Maribong Carabao Raisers Association (MARICARA)', 'WVSU', NULL, NULL, NULL, '3', 'Lambunao', 'Iloilo', 1, NULL, 'WVSU'),
('Visayas', 'VI', 'Western Visayas', 'Guinhulacan Farmers Association (GUFA)', 'WVSU', NULL, NULL, NULL, '3', 'Bingawan', 'Iloilo', 1, NULL, 'WVSU'),
('Visayas', 'VI', 'Western Visayas', 'Barotac Nuevo Development Cooperative', 'WVSU', NULL, NULL, NULL, '4', 'Barotac Nuevo', 'Iloilo', 1, NULL, 'WVSU'),
('Visayas', 'VI', 'Western Visayas', 'IFMultipurpose Cooperative', 'WVSU', NULL, NULL, NULL, NULL, 'Sara', 'Iloilo', 1, NULL, 'WVSU'),
('Visayas', 'VI', 'Western Visayas', 'Pandan Multipurpose Cooperative', 'WVSU', NULL, NULL, NULL, '1', 'Pandan', 'Antique', 1, NULL, 'WVSU'),
('Visayas', 'VI', 'Western Visayas', 'Hamtic Multipurpose Cooperative', 'WVSU', NULL, NULL, NULL, '1', 'Hamtic', 'Antique', 1, NULL, 'WVSU'),
('Visayas', 'VI', 'Western Visayas', 'CLB-CARES, INC.', 'WVSU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'WVSU'),
('Visayas', 'VI', 'Western Visayas', 'FAM. MOD.', 'WVSU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'WVSU'),
('Visayas', 'VI', 'Western Visayas', 'SMSRIFAI', 'WVSU', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'WVSU'),

-- VI Western Visayas - LCSF
('Visayas', 'VI', 'Western Visayas', 'PCC at LCSF IH', 'LCSF', NULL, NULL, NULL, NULL, NULL, 'Negros Occidental', NULL, NULL, 'LCSF'),
('Visayas', 'VI', 'Western Visayas', 'DSWD-SLP Dairy Module', 'LCSF', NULL, NULL, NULL, NULL, NULL, 'Negros Occidental', NULL, NULL, 'LCSF'),
('Visayas', 'VI', 'Western Visayas', 'DBE Dairy Modules', 'LCSF', NULL, NULL, NULL, NULL, NULL, 'Negros Occidental', NULL, NULL, 'LCSF'),
('Visayas', 'VI', 'Western Visayas', 'San Carlos City Livestock Center (SCCLC)', 'LCSF', NULL, NULL, NULL, NULL, 'San Carlos', 'Negros Occidental', NULL, NULL, 'LCSF'),
('Visayas', 'VI', 'Western Visayas', 'REI TIO (MILK COLLECTOR) (BASFA)(PAHILANGA)(PABILLARAN)', 'LCSF', NULL, NULL, NULL, NULL, NULL, 'Negros Occidental', NULL, NULL, 'LCSF'),
('Visayas', 'VI', 'Western Visayas', 'ISARFAWA', 'LCSF', NULL, NULL, NULL, '2', 'Pontevedra', 'Negros Occidental', 1, NULL, 'LCSF'),
('Visayas', 'VI', 'Western Visayas', 'Aksyon Binuligay Sagay Coconut Farmers Alliance', 'LCSF', NULL, NULL, NULL, '2', 'Sagay City', 'Negros Occidental', 1, NULL, 'LCSF'),
('Visayas', 'VI', 'Western Visayas', 'DGP FAMILY MODULE', 'LCSF', NULL, NULL, NULL, '3', 'E. B.MAGALONA', 'Negros Occidental', NULL, NULL, 'LCSF'),
('Visayas', 'VI', 'Western Visayas', 'FLORENTINO DAIRY MODULE', 'LCSF', NULL, NULL, NULL, '3', 'MURCIA', 'Negros Occidental', NULL, NULL, 'LCSF'),
('Visayas', 'VI', 'Western Visayas', 'BAGO CITY', 'LCSF', NULL, NULL, NULL, NULL, NULL, 'Negros Occidental', NULL, NULL, 'LCSF'),
('Visayas', 'VI', 'Western Visayas', 'CAUAYAN CITY', 'LCSF', NULL, NULL, NULL, NULL, NULL, 'Negros Occidental', NULL, NULL, 'LCSF'),
('Visayas', 'VI', 'Western Visayas', 'ILOG', 'LCSF', NULL, NULL, NULL, NULL, NULL, 'Negros Occidental', NULL, NULL, 'LCSF'),
('Visayas', 'VI', 'Western Visayas', 'SAN CARLOS CITY', 'LCSF', NULL, NULL, NULL, NULL, NULL, 'Negros Occidental', NULL, NULL, 'LCSF'),
('Visayas', 'VI', 'Western Visayas', 'KABANKALAN CITY', 'LCSF', NULL, NULL, NULL, NULL, NULL, 'Negros Occidental', NULL, NULL, 'LCSF'),
('Visayas', 'VI', 'Western Visayas', 'LA CASTELLANA', 'LCSF', NULL, NULL, NULL, NULL, NULL, 'Negros Occidental', NULL, NULL, 'LCSF'),
('Visayas', 'VI', 'Western Visayas', 'BINALBAGAN', 'LCSF', NULL, NULL, NULL, NULL, NULL, 'Negros Occidental', NULL, NULL, 'LCSF'),
('Visayas', 'VI', 'Western Visayas', 'ISABELA', 'LCSF', NULL, NULL, NULL, NULL, NULL, 'Negros Occidental', NULL, NULL, 'LCSF'),
('Visayas', 'VI', 'Western Visayas', 'HIMAMAYLAN CITY', 'LCSF', NULL, NULL, NULL, NULL, NULL, 'Negros Occidental', NULL, NULL, 'LCSF'),
('Visayas', 'VI', 'Western Visayas', 'MINURO AGRARIAN REFORM COOPERATIVE', 'LCSF', NULL, NULL, NULL, '3', 'Victorias City', 'Negros Occidental', NULL, NULL, 'LCSF'),
('Visayas', 'VI', 'Western Visayas', 'San Antonio Farmers Multi-Purpose Cooperative', 'LCSF', NULL, NULL, NULL, '3', 'Victorias City', 'Negros Occidental', NULL, NULL, 'LCSF'),
('Visayas', 'VI', 'Western Visayas', 'Associated Planters Cooperative of Silay-Saravia(APCOSS)', 'LCSF', NULL, NULL, NULL, '3', 'E.B. MAGALONA', 'Negros Occidental', NULL, NULL, 'LCSF'),

-- VII Central Visayas
('Visayas', 'VII', 'Central Visayas', 'San Julio ARB Cooperative (Processor)', 'LCSF', NULL, NULL, NULL, '3', 'Tanjay City', 'Negros Oriental', 1, NULL, 'LCSF'),
('Visayas', 'VII', 'Central Visayas', 'Bayawan Dairy Farmers Cooperative (BADAFCO) (DRA Dairy Module)', 'LCSF', NULL, NULL, NULL, '3', 'Bayawan', 'Negros Oriental', 1, NULL, 'LCSF'),
('Visayas', 'VII', 'Central Visayas', 'GUIHULNGAN CITY', 'LCSF', NULL, NULL, NULL, NULL, NULL, 'Negros Oriental', NULL, NULL, 'LCSF'),
('Visayas', 'VII', 'Central Visayas', 'BAYAWAN CITY', 'LCSF', NULL, NULL, NULL, NULL, NULL, 'Negros Oriental', NULL, NULL, 'LCSF'),
('Visayas', 'VII', 'Central Visayas', 'PALMA FAMILY MODULE', 'LCSF', NULL, NULL, NULL, '4', 'BAGO CITY', 'Negros Oriental', NULL, NULL, 'LCSF'),
('Visayas', 'VII', 'Central Visayas', 'PUPA DAIRY MODULE', 'LCSF', NULL, NULL, NULL, '4', 'BAGO CITY', 'Negros Oriental', NULL, NULL, 'LCSF'),
('Visayas', 'VII', 'Central Visayas', 'Samoyao Hills Pamplona Producers Cooperative', 'LCSF', NULL, NULL, NULL, '2', 'Pamplona', 'Negros Oriental', 1, NULL, 'LCSF'),
('Visayas', 'VII', 'Central Visayas', 'Rebutazo Dairy Module', 'LCSF', NULL, NULL, NULL, '2', 'Pamplona', 'Negros Oriental', NULL, NULL, 'LCSF'),
('Visayas', 'VII', 'Central Visayas', 'MDM', 'LCSF', NULL, NULL, NULL, '1', 'CANLAON CITY', 'Negros Oriental', NULL, NULL, 'LCSF'),
('Visayas', 'VII', 'Central Visayas', 'SAN JUAN MULTIPURPOSE Cooperative', 'LCSF', NULL, NULL, NULL, '3', 'San Juan', 'SIQUIJOR', 1, NULL, 'LCSF'),

-- VII Central Visayas - USF
('Visayas', 'VII', 'Central Visayas', 'PCC at USF IH', 'USF', NULL, NULL, NULL, '2', 'Ubay', 'Bohol', NULL, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Bohol Dairy Cooperative', 'USF', NULL, NULL, NULL, '2', 'Ubay', 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Abaca Smile Dairy Association (2018 New)', 'USF', NULL, NULL, NULL, NULL, NULL, 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Aguipo Farmer''s Association', 'USF', NULL, NULL, NULL, NULL, NULL, 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Biabas Ubay Dairy Association', 'USF', NULL, NULL, NULL, NULL, NULL, 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Bongbong Dairy Breeders Association', 'USF', NULL, NULL, NULL, NULL, NULL, 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Bugang Farmers Association', 'USF', NULL, NULL, NULL, NULL, 'Bugang', 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Cadapdapan Escaya Tribe Association', 'USF', NULL, NULL, NULL, NULL, 'Candijay', 'Bohol', NULL, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Libertad Multi-purpose Cooperative', 'USF', NULL, NULL, NULL, '1', 'Tubigon', 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Bongbong SMILE Dairy Association', 'USF', NULL, NULL, NULL, '2', 'Ubay', 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Gabi Carabao Raiser''s Association', 'USF', NULL, NULL, NULL, '2', 'Ubay', 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Katarungan Small Coconut Farmers Multi-Purpose Cooperative (KSCFMultipurpose Cooperative)', 'USF', NULL, NULL, NULL, '1', 'Katarungan', 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Progreso Womens and Workers Multi-Purpose Cooperative', 'USF', NULL, NULL, NULL, NULL, NULL, 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Riceland Paradise Multi-Purpose Cooperative', 'USF', NULL, NULL, NULL, '2', 'Ubay', 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'San Jose Buffalo Dairy Producers Association', 'USF', NULL, NULL, NULL, '1', 'San Jose', 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'San Miguel Multi-Purpose Cooperative', 'USF', NULL, NULL, NULL, '2', 'San Miguel', 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'San Pascual Dairy Breeders Association', 'USF', NULL, NULL, NULL, NULL, NULL, 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'San Roque Lungsoddaan Mabini Fishersmen and Farmers Multi-purpose Cooperative', 'USF', NULL, NULL, NULL, NULL, NULL, 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Ubay Northeastern Dairy Breeder''s Association', 'USF', NULL, NULL, NULL, '2', 'Ubay', 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Ubay Northwestern Dairy Breeders Association', 'USF', NULL, NULL, NULL, NULL, NULL, 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Village Dairy Farmers Association', 'USF', NULL, NULL, NULL, NULL, NULL, 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Untaga Multi Purpose Cooperative', 'USF', NULL, NULL, NULL, '1', 'Untaga', 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Gov. Boyles Carabao Raisers Association', 'USF', NULL, NULL, NULL, '2', 'Ubay', 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'La Hacienda People''s Organization', 'USF', NULL, NULL, NULL, '2', 'Ubay', 'Bohol', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Lamac Multipurpose Cooperative', 'USF', NULL, NULL, NULL, '2', 'Pinamungajan', 'Cebu', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'First Consolidated Cooperative Along the Tanon Seaboard', 'USF', NULL, NULL, NULL, '5', 'Tuburan', 'Cebu', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Compostela Dairy Farmers Multipurpose Cooperative', 'USF', NULL, NULL, NULL, '5', 'Compostela', 'Cebu', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'CEFEDCO/Lusaran Alayon Farmers Multipurpose Cooperative', 'USF', NULL, NULL, NULL, '7', 'Pinamungajan', 'Cebu', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Compostela Market Vendors Multi-Purpose Cooperative', 'USF', NULL, NULL, NULL, '5', 'Compostela', 'Cebu', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'LGU-Compostela', 'USF', NULL, NULL, NULL, '5', 'Compostela', 'Cebu', NULL, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', 'Campinsa Manipis Multi-purpose Cooperative', 'USF', NULL, NULL, NULL, '1', 'Talisay', 'Cebu', 1, NULL, 'USF'),
('Visayas', 'VII', 'Central Visayas', NULL, 'USF', NULL, NULL, NULL, NULL, NULL, 'Siquijor', NULL, NULL, 'USF'),
('Visayas', 'V', 'Bicol Region', 'Queenscup Agrarian Reform and Marginal Farmers Cooperative', 'USF', NULL, NULL, NULL, NULL, 'Placer', 'Masbate', 1, NULL, 'USF'),

-- VIII Eastern Visayas
('Visayas', 'VIII', 'Eastern Visayas', 'Lico Agrarian Reform Cooperative', 'VSU', NULL, NULL, NULL, '1', 'Naval', 'Biliran', 1, NULL, 'VSU'),
('Visayas', 'VIII', 'Eastern Visayas', 'Almeria Seafarer''s Multi-Purpose Cooperative', 'VSU', NULL, NULL, NULL, '1', 'Biliran', 'Biliran', 1, NULL, 'VSU'),
('Visayas', 'VIII', 'Eastern Visayas', NULL, 'VSU', NULL, NULL, NULL, NULL, NULL, 'Eatern Samar', NULL, NULL, 'VSU'),
('Visayas', 'VIII', 'Eastern Visayas', 'Hibobollao Multi Purpose Cooperative', 'VSU', NULL, NULL, NULL, '2', 'Catubig', 'Northern Samar', 1, NULL, 'VSU'),
('Visayas', 'VIII', 'Eastern Visayas', 'Kalingnan Community Farmers association', 'VSU', NULL, NULL, NULL, '2', 'Catubig', 'Northern Samar', NULL, NULL, 'VSU'),
('Visayas', 'VIII', 'Eastern Visayas', 'Samar Multi-Purpose Cooperative', 'VSU', NULL, NULL, NULL, '2', 'Basey', 'Samar', 1, NULL, 'VSU'),
('Visayas', 'VIII', 'Eastern Visayas', 'San Antonio Farmers and Fisherfolk Association', 'VSU', NULL, NULL, NULL, '2', 'Basey', 'Samar', NULL, NULL, 'VSU'),
('Visayas', 'VIII', 'Eastern Visayas', 'Villareal Dairy Processors Association', 'VSU', NULL, NULL, NULL, '2', 'Villareal', 'Samar', 1, NULL, 'VSU'),
('Visayas', 'VIII', 'Eastern Visayas', 'PCC at VSU IH', 'VSU', NULL, NULL, NULL, '5', 'Baybay', 'Leyte', NULL, NULL, 'VSU'),
('Visayas', 'VIII', 'Eastern Visayas', 'Baybay Dairy Cooperative', 'VSU', NULL, NULL, NULL, '5', 'Baybay', 'Leyte', 1, NULL, 'VSU'),
('Visayas', 'VIII', 'Eastern Visayas', 'Brgy. Biasong Community Association', 'VSU', NULL, NULL, NULL, '5', 'Baybay', 'Leyte', 1, NULL, 'VSU'),
('Visayas', 'VIII', 'Eastern Visayas', 'Javier Dairy Buffalo Multiplier Farm', 'VSU', NULL, NULL, NULL, '5', 'Javier', 'Leyte', NULL, NULL, 'VSU'),
('Visayas', 'VIII', 'Eastern Visayas', 'Omaganhan Farmers Agrarian Reform Cooperative', 'VSU', NULL, NULL, NULL, '5', 'Tabango', 'Leyte', 1, NULL, 'VSU'),
('Visayas', 'VIII', 'Eastern Visayas', 'Gandara Breeding Station', 'VSU', NULL, NULL, NULL, NULL, NULL, 'Leyte', NULL, NULL, 'VSU'),
('Visayas', 'VIII', 'Eastern Visayas', 'Macalpi Community Multipurpose Cooperative', 'VSU', NULL, NULL, NULL, '1', 'Macalpe', 'Leyte', 1, NULL, 'VSU'),
('Visayas', 'VIII', 'Eastern Visayas', 'Kangara Multi Purpose Cooperative', 'VSU', NULL, NULL, NULL, '2', 'Carigara', 'Leyte', 1, NULL, 'VSU'),
('Visayas', 'VIII', 'Eastern Visayas', 'Canila Multi Purpose Cooperative', 'VSU', NULL, NULL, NULL, '3', 'Carigara', 'Leyte', 1, NULL, 'VSU'),
('Visayas', 'VIII', 'Eastern Visayas', 'Pinoy Multi-purpose Cooperative', 'VSU', NULL, NULL, NULL, NULL, 'Maasin City', 'Southern Leyte', 1, NULL, 'VSU'),

-- IX Zamboanga Peninsula
('Mindanao', 'IX', 'Zamboanga Peninsula', 'PCC at MLPC IH', 'MLPC', NULL, NULL, NULL, '3', NULL, 'Zamboanga del Norte', NULL, NULL, 'MLPC'),
('Mindanao', 'IX', 'Zamboanga Peninsula', 'Sindangan Crossbred Buffalo Raisers Association', 'MLPC', NULL, NULL, NULL, '2', 'Sindangan', 'Zamboanga del Norte', 1, NULL, 'MLPC'),
('Mindanao', 'IX', 'Zamboanga Peninsula', 'Siari Valley Agrarian Reform Beneficiaries Multipurpose Cooperative', 'MLPC', NULL, NULL, NULL, '2', 'Sindangan', 'Zamboanga del Norte', 1, NULL, 'MLPC'),
('Mindanao', 'IX', 'Zamboanga Peninsula', 'Jose Rizal Memorial State University (KNAS/JRMSU)', 'MLPC', NULL, NULL, NULL, '2', 'Katipunan', 'Zamboanga del Norte', NULL, NULL, 'MLPC'),
('Mindanao', 'IX', 'Zamboanga Peninsula', 'Pro.Vet-LGU - Irasan', 'MLPC', NULL, NULL, NULL, '2', 'Roxas', 'Zamboanga del Norte', NULL, NULL, 'MLPC'),
('Mindanao', 'IX', 'Zamboanga Peninsula', 'Antipolo Primary Mutipurpose Agri Cooperative- CBIN', 'MLPC', NULL, NULL, NULL, '1', 'Dapitan and Pulanco', 'Zamboanga del Norte', 1, NULL, 'MLPC'),
('Mindanao', 'IX', 'Zamboanga Peninsula', 'Liloy Carabao Raisers Association', 'MLPC', NULL, NULL, NULL, '3', 'Liloy', 'Zamboanga del Norte', 1, NULL, 'MLPC'),
('Mindanao', 'IX', 'Zamboanga Peninsula', 'Polanco Carabao Breeders and Raisers Association', 'MLPC', NULL, NULL, NULL, '2', 'Polanco', 'Zamboanga del Norte', 1, NULL, 'MLPC'),
('Mindanao', 'IX', 'Zamboanga Peninsula', 'Baclay Multipurpose Cooperative- CBIN', 'MLPC', NULL, NULL, NULL, '2', 'Dumalinao and Tukuran', 'Zamboanga del Sur', 1, NULL, 'MLPC'),
('Mindanao', 'IX', 'Zamboanga Peninsula', 'Ipil Community Multi-Purpose Cooperative', 'MLPC', NULL, NULL, NULL, '2', 'Ipil', 'Zamboanga Sibugay', 1, NULL, 'MLPC'),
('Mindanao', 'IX', 'Zamboanga Peninsula', 'Ipilinos carabao Farmers Association', 'MLPC', NULL, NULL, NULL, '2', 'Ipil', 'Zamboanga Sibugay', 1, NULL, 'MLPC'),

-- X Northern Mindanao
('Mindanao', 'X', 'Northern Mindanao', 'PCC at CMU IH', 'CMU', NULL, NULL, NULL, NULL, NULL, 'Bukidnon', NULL, NULL, 'CMU'),
('Mindanao', 'X', 'Northern Mindanao', 'Don Carlos Buffalo Farmers Dairy Cooperative', 'CMU', NULL, NULL, NULL, '3', 'Don Carlos', 'Bukidnon', 1, NULL, 'CMU'),
('Mindanao', 'X', 'Northern Mindanao', 'Dologon Kisanday Buffalo Dairy Assoc', 'CMU', NULL, NULL, NULL, '3', 'Maramag', 'Bukidnon', 0, NULL, 'CMU'),
('Mindanao', 'X', 'Northern Mindanao', 'USWAG Bukidnon, Inc.', 'CMU', NULL, NULL, NULL, '3', 'Maramag', 'Bukidnon', NULL, NULL, 'CMU'),
('Mindanao', 'X', 'Northern Mindanao', 'Balugto "Hope" Agriculture Cooperative', 'CMU', NULL, NULL, NULL, NULL, 'Talakag', 'Bukidnon', NULL, NULL, 'CMU'),
('Mindanao', 'X', 'Northern Mindanao', 'TAGOLOAN Farms Agri Cooperative', 'CMU', NULL, NULL, NULL, NULL, 'Manolo Fortich', 'Bukidnon', 1, NULL, 'CMU'),
('Mindanao', 'X', 'Northern Mindanao', NULL, 'CMU', NULL, NULL, NULL, NULL, NULL, 'Camiguin', NULL, NULL, 'CMU'),
('Mindanao', 'X', 'Northern Mindanao', 'Oro Integrated Cooperative', 'CMU', NULL, NULL, NULL, '2', 'Cagayan de Oro', 'Misamis Oriental', 1, NULL, 'CMU'),
('Mindanao', NULL, NULL, 'San Roque Dairy Farm', 'CMU', NULL, NULL, NULL, NULL, 'El Salvador City', 'Misamis Oriental', 0, NULL, 'CMU'),
('Mindanao', 'X', 'Northern Mindanao', '(TOMAMA) Toboron Mapulog Maputi Agrarian Reform Community Marketing Cooperative', 'CMU', NULL, NULL, NULL, '2', 'Naawan', 'Misamis Oriental', NULL, NULL, 'CMU'),
('Mindanao', 'X', 'Northern Mindanao', 'Paglaum MultiPurpose Cooperative', 'CMU', NULL, NULL, NULL, '1', 'Plaridel', 'Misamis Occidental', 1, NULL, 'CMU'),
('Mindanao', 'X', 'Northern Mindanao', 'El Pasyalan Dairy Farm', 'CMU', NULL, NULL, NULL, NULL, 'Jimenez', 'Misamis Occidental', NULL, NULL, 'CMU'),
('Mindanao', 'X', 'Northern Mindanao', NULL, 'CMU', NULL, NULL, NULL, NULL, NULL, 'Lanao del Norte', NULL, NULL, 'CMU'),

-- XI Davao Region
('Mindanao', 'XI', 'Davao Region', 'Linoan Farmers Integrated Cooperative', 'USM', NULL, NULL, NULL, '1', 'Montevista', 'Davao de Oro (CBIN)', 1, NULL, 'USM'),
('Mindanao', 'XI', 'Davao Region', 'Braulio E. Dujali Farmer''s Livestock Raisers and Dairy Workers Association (BEDFLRDWA)', 'USM', NULL, NULL, NULL, '2', 'BE Dujali', 'Davao Del Norte', 1, NULL, 'USM'),
('Mindanao', 'XI', 'Davao Region', 'Inyam Pintuan Asbang Multipurpose Cooperative', 'USM', NULL, NULL, NULL, '1', 'Matanao', 'Davao del Sur (CBIN)', 1, NULL, 'USM'),
('Mindanao', 'XI', 'Davao Region', 'LGU Kiblawan', 'USM', NULL, NULL, NULL, '2', 'Kiblawan', 'Davao del Sur (CBIN)', NULL, NULL, 'USM'),
('Mindanao', 'XI', 'Davao Region', 'Kalaparan Agrarian Reform Beneficiaries Assn', 'USM', NULL, NULL, NULL, '2', 'Mati City', 'Davao Oriental(CBIN)', 1, NULL, 'USM'),
('Mindanao', 'XI', 'Davao Region', 'Taytayan Irrigators and Farmers Multi-Purpose Cooperative', 'USM', NULL, NULL, NULL, '1', 'Cateel', 'Davao Oriental(CBIN)', 1, NULL, 'USM'),
('Mindanao', 'XI', 'Davao Region', 'Felbert Tradio(New)', 'USM', NULL, NULL, NULL, NULL, NULL, 'Davao Occidental', NULL, NULL, 'USM'),
('Mindanao', 'XI', 'Davao Region', '(UNICARBAI) United CARP Beneficiaries Association Incorporated Multipurpose Cooperative', 'USM', NULL, NULL, NULL, '1', 'sta. maria', 'Davao Occidental', 1, NULL, 'USM'),

-- XII Soccsksargen
('Mindanao', 'XII', 'Soccsksargen', 'PCC at USM IH', 'USM', NULL, NULL, NULL, NULL, NULL, 'North Cotabato', NULL, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'D and L Dairy Farm', 'USM', NULL, NULL, NULL, '3', 'M''lang', 'North Cotabato', NULL, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'OND Genesis Farm (NEW)', 'USM', NULL, NULL, NULL, '2', 'Makilala', 'North Cotabato', NULL, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'Dolores Farmers Association', 'USM', NULL, NULL, NULL, '2', 'Makilala', 'North Cotabato', 1, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'Deo Estestes (Family Module)', 'USM', NULL, NULL, NULL, '1', 'Aleosan', 'North Cotabato', NULL, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'Aveliza Cantero', 'USM', NULL, NULL, NULL, '1', 'Midsayap', 'North Cotabato', NULL, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'Fidelito Dorado', 'USM', NULL, NULL, NULL, '2', 'Pres. Roxas', 'North Cotabato', NULL, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'Cotabato Foundation College and Science Technology', 'USM', NULL, NULL, NULL, '2', 'Arakan', 'North Cotabato', NULL, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'Sta. Catalina Multipurpose Cooperative', 'USM', NULL, NULL, NULL, '2', 'Pres. Roxas', 'North Cotabato(CBIN)', 1, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'Surallah LGU Enterprise', 'USM', NULL, NULL, NULL, '3', 'Surallah', 'South Cotabato', NULL, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'Canahay Dairy Farmers Association', 'USM', NULL, NULL, NULL, '3', 'Surallah', 'South Cotabato', 1, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'Remie Omodto (Family Module)', 'USM', NULL, NULL, NULL, '3', 'Surallah', 'South Cotabato', NULL, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'Highland Agricultural Credit Cooperative', 'USM', NULL, NULL, NULL, '3', 'Lake Cebu', 'South Cotabato(CBIN)', 1, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'Joselino Cabino', 'USM', NULL, NULL, NULL, '3', 'Surallah', 'South Cotabato', NULL, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'Dante Parreñas', 'USM', NULL, NULL, NULL, '3', 'Sto. Niño', 'South Cotabato', 1, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'Abner Panaligan', 'USM', NULL, NULL, NULL, '3', 'Sto. Niño', 'South Cotabato', NULL, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'Marlon Recidoro', 'USM', NULL, NULL, NULL, '3', 'Sto. Niño', 'South Cotabato', NULL, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'Joel Bacongco', 'USM', NULL, NULL, NULL, '2', 'Koronadal', 'South Cotabato', NULL, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'May Dubla', 'USM', NULL, NULL, NULL, '3', 'Surallah', 'South Cotabato', NULL, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'Joe an Sevillo', 'USM', NULL, NULL, NULL, '3', 'Surallah', 'South Cotabato', NULL, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'Animal Production and Processing Center', 'USM', NULL, NULL, NULL, '2', 'Tantangan', 'South Cotabato', NULL, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'Coconut Carabao Development Project (CCDP)', 'USM', NULL, NULL, NULL, '1&2', 'Tupi/Tampakan/Banga', 'South Cotabato', NULL, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'Tupi Integrated Agricultural Cooperative', 'USM', NULL, NULL, NULL, '1', 'Tupi', 'South Cotabato', 1, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'Pangi Multipurpose Cooperative', 'USM', NULL, NULL, NULL, NULL, 'Maitum', 'Sarangani', 1, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'Alabel Dairy Farmers Association', 'USM', NULL, NULL, NULL, NULL, 'Alabel', 'Sarangani', NULL, NULL, 'USM'),
('Mindanao', 'XII', 'Soccsksargen', 'James Reamon', 'USM', NULL, NULL, NULL, NULL, 'General Santos City', 'Sarangani', NULL, NULL, 'USM'),
('Mindanao', 'BARMM', 'BARMM', 'LGU-Upi', 'USM', NULL, NULL, NULL, NULL, 'Upi', 'Maguindanao', NULL, NULL, 'USM'),

-- CARAGA
('Mindanao', 'CARAGA', NULL, 'NORMISIST/CSU- Caraga State University', 'CMU', NULL, NULL, NULL, '1', 'Butuan City', 'Agusan Del Norte', NULL, NULL, 'CMU'),
('Mindanao', 'CARAGA', NULL, '(MAFCO) Maong Agrarian Farmers Cooperative', 'CMU', NULL, NULL, NULL, '1', 'Cabadbaran City', 'Agusan Del Norte', 1, NULL, 'CMU'),
('Mindanao', 'CARAGA', NULL, 'Katipunan Farmer Producers Cooperative', 'CMU', NULL, NULL, NULL, '1', 'Bayugan City', 'Agusan del Sur', 1, NULL, 'CMU'),
('Mindanao', 'CARAGA', NULL, 'San Francisco Farmers Producers Cooperative', 'CMU', NULL, NULL, NULL, '1', 'San Francisco', 'Agusan del Sur', 1, NULL, 'CMU'),
('Mindanao', 'CARAGA', NULL, NULL, 'CMU', NULL, NULL, NULL, NULL, NULL, 'Dinagat Islands', NULL, NULL, 'CMU'),
('Mindanao', 'CARAGA', NULL, 'Trinidad Sustainable Livelihood Association', 'CMU', NULL, NULL, NULL, '1', 'Surigao City', 'Surigao Del Norte', 1, NULL, 'CMU'),
('Mindanao', 'CARAGA', NULL, '(BCGEMCO) Bislig Community Government Employees Cooperative', 'CMU', NULL, NULL, NULL, '2', 'Bislig City', 'Surigao Del Sur', 1, NULL, 'CMU'),

-- BARRM
('Mindanao', 'BARRM', NULL, NULL, 'MLPC', NULL, NULL, NULL, NULL, NULL, 'Basilan', NULL, NULL, 'MLPC'),
('Mindanao', 'BARRM', NULL, NULL, 'MLPC', NULL, NULL, NULL, NULL, NULL, 'Lanao Del Norte', NULL, NULL, 'MLPC'),
('Mindanao', 'BARRM', NULL, NULL, 'MLPC', NULL, NULL, NULL, NULL, NULL, 'Lanao Del Sur', NULL, NULL, 'MLPC'),
('Mindanao', 'BARRM', NULL, NULL, 'MLPC', NULL, NULL, NULL, NULL, NULL, 'Maguindanao', NULL, NULL, 'MLPC'),
('Mindanao', 'BARRM', NULL, NULL, 'MLPC', NULL, NULL, NULL, NULL, NULL, 'Sulu', NULL, NULL, 'MLPC'),
('Mindanao', 'BARRM', NULL, NULL, 'MLPC', NULL, NULL, NULL, NULL, NULL, 'Tawi Tawi', NULL, NULL, 'MLPC');